//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KakaotalkAdConcealer.Forms.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KakaotalkAdConcealer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate at startup.
        /// </summary>
        internal static string ActivateAtStartup {
            get {
                return ResourceManager.GetString("ActivateAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already activated.
        /// </summary>
        internal static string AlreadyActivated {
            get {
                return ResourceManager.GetString("AlreadyActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed task.
        /// </summary>
        internal static string CompletedTask {
            get {
                return ResourceManager.GetString("CompletedTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goodbye, Ads.
        /// </summary>
        internal static string GoodbyeAds {
            get {
                return ResourceManager.GetString("GoodbyeAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all ads.
        /// </summary>
        internal static string RemoveAllAds {
            get {
                return ResourceManager.GetString("RemoveAllAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove embedded ads once.
        /// </summary>
        internal static string RemoveEmbeddedAdsOnce {
            get {
                return ResourceManager.GetString("RemoveEmbeddedAdsOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove popup ads once.
        /// </summary>
        internal static string RemovePopupAdsOnce {
            get {
                return ResourceManager.GetString("RemovePopupAdsOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ads blocker is running now!.
        /// </summary>
        internal static string RunningNow {
            get {
                return ResourceManager.GetString("RunningNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kakaotalk ad concealer.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
